Fix ARM64 REPL private helper calls and retain CI diagnostics

diff --git a/test/repl/Makefile b/test/repl/Makefile
--- a/test/repl/Makefile
+++ b/test/repl/Makefile
@@ -11,13 +11,20 @@ RESFILES=$(RES_NB_FILES) $(RES_B_FILES)
 MLKIT=../../bin/mlkit
 MLKIT_FLAGS?=-no_gc
 
+# Expected nonzero exits are explicit in <test>.status.ok (chdir tests EOF).
+# Keep outputs when a compiler/runtime failure interrupts the suite.
+.PRECIOUS: %-ri.out %-ri-nb.out
+
 .PHONY: all
 all: test
 
 %-ri-nb.out: %.cmd Makefile
-	@echo "SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) -no_basislib < $< | .. | .. > $@" >> complog.txt
-	@SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) -no_basislib < $< \
-           | grep -v 'MLKit v' \
+	@echo "SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) -no_basislib < $< > $@.log 2> $@.err" >> complog.txt
+	@status=0; SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) -no_basislib < $< > $@.log 2> $@.err || status=$$?; \
+         expected=0; if [ -f $*.status.ok ]; then expected=$$(cat $*.status.ok); fi; \
+         if [ "$$expected" = nonzero ]; then [ $$status -ne 0 ]; else [ $$status -eq $$expected ]; fi || \
+         { cat $@.err >&2; echo "REPL exit status $$status (expected $$expected)" >&2; exit 1; }
+	@grep -v 'MLKit v' < $@.log \
            | grep -v 'Garbage collection disabled' \
            | grep -v 'Basis Library and Pretty Printing not loaded' \
            | grep -v 'Type :help;' \
@@ -38,9 +45,12 @@ all: test
 	@cat $@ >> complog.txt
 
 %-ri.out: %.cmd Makefile
-	@echo "SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) < $< | .. | .. > $@" >> complog.txt
-	@SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) < $< \
-           | grep -v 'MLKit v' \
+	@echo "SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) < $< > $@.log 2> $@.err" >> complog.txt
+	@status=0; SML_LIB=../.. $(MLKIT) $(MLKIT_FLAGS) < $< > $@.log 2> $@.err || status=$$?; \
+         expected=0; if [ -f $*.status.ok ]; then expected=$$(cat $*.status.ok); fi; \
+         if [ "$$expected" = nonzero ]; then [ $$status -ne 0 ]; else [ $$status -eq $$expected ]; fi || \
+         { cat $@.err >&2; echo "REPL exit status $$status (expected $$expected)" >&2; exit 1; }
+	@grep -v 'MLKit v' < $@.log \
            | grep -v 'Garbage collection disabled' \
            | grep -v 'Basis Library and Pretty Printing not loaded' \
            | grep -v 'Type :help;' \
@@ -75,4 +85,4 @@ prepare:
 
 .PHONY: clean
 clean:
-	rm -rf MLB *~ *.res *.out complog.txt run
+	rm -rf MLB *~ *.res *.out *.out.log *.out.err complog.txt run
