MLKit 64bit (#25)
MLKit now generates 64bit assembler under both Linux and macOS for all combinations of GC, Region-based memory management, and profiling. All tests are working, including the following targets:

* `make mlkit`
* `make mlkit_libs`
* `(cd test_dev; make test)`
* `(cd test; make test_mlkit)``
* `make bootstrap`

There are a number of possibilities for improvements and features that are not currently included. In particular, the KAM backend, which is the basis for SMLserver, has not yet been ported. 

Possibilities for improvements include:

* Elimination of the `gen->b` pointer (use alignment properties instead).
* Inlining of allocation in regions (for the common case).
* Figure out how to assign certain C callee-save registers to variables that are live across C calls.
* Many peep-hole optimisations seem possible.
* Eliminate the need for dynamic stack alignment on 16-byte boundaries.
* Test the preliminary support for generational garbage collection.
* Use conditional move instructions instead of conditional jumps when possible.
* Add Word64 and Word63 modules and friends. Whenever we have WordX, we should also have IntX. We should then also modify the default word type to be Word64.word if GC is disabled and Word63.word if GC is enabled. Immediate constants of size 64 and 63 should also be supported.

diff --git a/src/CUtils/Makefile b/src/CUtils/Makefile
--- a/src/CUtils/Makefile
+++ b/src/CUtils/Makefile
@@ -1,15 +1,38 @@
+RESFILES=hashmap_typed_test.res binaryheap_test.res
+CFLAGS=-Wall -pedantic
+
 .PHONY: all
+all: test
 
-all: hashmap_typed_test binaryheap_test
+hashmap_typed_test.out:
+	gcc $(CFLAGS) hashmap.c hashmap_typed.c hashmap_typed_test.c
+	./a.out > $@
 
-hashmap_typed_test:
-	gcc hashmap.c hashmap_typed.c hashmap_typed_test.c
-	./a.out
+binaryheap_test.out:
+	gcc $(CFLAGS) binaryheap_test.c
+# @echo "output should be: 5 4 1 7 2 3 6"
+	./a.out 3 4 5 2 1 6 3 > $@
 
-binaryheap_test: 
-	gcc -Wall -pedantic binaryheap_test.c
-	@echo "output should be: 5 4 1 7 2 3 6"
-	./a.out 3 4 5 2 1 6 3 
+%.res: %.out
+	@(diff -aq $< $<.ok > /dev/null 2>&1; \
+         if [ $$? -eq 0 ]; then \
+             echo "Test $*: OK" > $@ \
+         ; else \
+             if [ -e $<.ok ]; then \
+                echo "Test $*: *** ERR: file $< differs from $<.ok ***" > $@ \
+             ; else \
+                echo "Test $*: *** ERR: file $<.ok does not exist ***" > $@ \
+             ; fi \
+         ; fi)
+
+.PHONY: test
+test: $(RESFILES)
+	@cat $(RESFILES)
+	@echo "-------T E S T --- R E P O R T-------"
+	@echo "Tests succeeded:   `grep "OK" $(RESFILES) | wc -l` /`grep "Test" $(RESFILES) | wc -l`"
+	@echo "Test errors:       `grep "ERR" $(RESFILES) | wc -l` /`grep "Test" $(RESFILES) | wc -l`"
+	@echo "-------------------------------------"
+	@exit `grep "ERR" $(RESFILES) | wc -l`
 
 clean:
-	rm -rf *~ a.out *.o
+	rm -rf *~ *.o *.res *.out
